# Generated by Django 5.2.4 on 2025-07-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roupa',
            name='categoria',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='roupa',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='roupas/'),
        ),
    ]
